triggers:
- envs: []
  name: green_taxi_to_gcs
  pipeline_uuid: green_taxi_etl
  schedule_interval: '@daily'
  schedule_type: time
  settings:
    landing_time_enabled: false
  sla: null
  start_time: 2024-01-29 05:00:00
  status: active
  variables: {}
